=== li12242/fluidity/tools/regressiontest.dtd
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--++ A dtd defining regression test problems                    ++-->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->

<!ELEMENT testproblem (name,tags,problem_definition,variables,pass_tests,warn_tests)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT owner (#PCDATA)>

<!ELEMENT tags (tag*)>
<!ELEMENT tag (#PCDATA)>

<!-- problem_definition might eventually contain information about
such things as number of nodes to run on. -->
<!ELEMENT problem_definition (command_line)>
<!ATTLIST problem_definition length (short|medium|long|special) #REQUIRED
                             nprocs CDATA #REQUIRED>

<!ELEMENT command_line (#PCDATA)>

<!ELEMENT variables (variable*)>

<!-- A variable (to be used in python tests) is defined by the value
of either a python expression or a bash expresion. -->
<!ELEMENT variable (#PCDATA)>
<!ATTLIST variable name NMTOKEN       #REQUIRED
                   language (python|bash) #REQUIRED>

<!ELEMENT pass_tests (test*)>

<!ELEMENT warn_tests (test*)>

<!-- A test is a python or bash expression which returns a python true 
value or bash successful completion for pass and a python 
false value or bash fail for fail. -->
<!ELEMENT test (#PCDATA)>
<!ATTLIST test name NMTOKEN       #REQUIRED
                   language (python|bash) #REQUIRED>

=== li12242/fluidity/tests/bingham-slope/bingham-slope.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>Visco-elastic solid block test</name>
  <owner userid="cwilson"/>
  <tags>flml solidity</tags>
    <problem_definition length="medium" nprocs="1">
    <command_line>dfluidity --xml lagrangian_bingham_slope.flml  </command_line>
  </problem_definition>  
  <variables>  
    <variable name="maxxvel" language="python">
import vtktools
vtufile=vtktools.vtu('lagrangian_bingham_slope_1.vtu')
velocity = vtufile.GetVectorField('Velocity') 
maxxvel=max(velocity[:,0])
   </variable>    
    <variable name="minxvel" language="python">
import vtktools
vtufile=vtktools.vtu('lagrangian_bingham_slope_1.vtu')
velocity = vtufile.GetVectorField('Velocity') 
minxvel=min(velocity[:,0])
   </variable>    
    <variable name="maxxpos" language="python">
import vtktools
vtufile=vtktools.vtu('lagrangian_bingham_slope_1.vtu')
pos = vtufile.GetLocations()
maxxpos=max(pos[:,0])
   </variable>    
    <variable name="maxypos" language="python">
import vtktools
vtufile=vtktools.vtu('lagrangian_bingham_slope_1.vtu')
pos = vtufile.GetLocations()
maxypos=max(pos[:,1])
   </variable>    
  </variables>
    <pass_tests>  
    <test name="check maximum x velocity is negative" language="python">
   assert maxxvel &lt; 1e-10
    </test>    
    <test name="check minimum x velocity is negative" language="python">
   assert minxvel &lt; 1e-10
    </test>    
    <test name="check maximum x coordinate is bigger than 3.2 (its original position)" language="python">
   assert maxxpos &gt; 3.2
    </test>    
    <test name="check maximum y coordinate is less than 1.0 (its original position)" language="python">
   assert maxypos &lt; 1.0
    </test>    
    <test name="check maximum x coordinate is 3.2" language="python">
   assert abs(maxxpos-3.2) &lt; 1.E-1
    </test>
    <test name="check maximum y coordinate is 0.8" language="python">
   assert abs(maxypos-0.8) &lt; 1.E-1
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/legacy_reservoir_prototype/tests/BL_test_gravity/BL_test_gravity.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>BL_test_1d</name>
  <owner userid="Bob"/>
  <tags></tags>
  <problem_definition length="medium" nprocs="1">
    <command_line>
       ../../bin/MultiphasePrototype.bin input.dat
    </command_line>
    <!-- One dimensional problem for BL equation -->
  </problem_definition>
  <variables>

  </variables>
  <pass_tests>

  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/burgers_adjoint_bc/burgers_adjoint_bc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">
<testproblem>
  <name>Burgers Equation BC</name>
  <owner userid="pef"/>
  <tags>burgers</tags>
  <problem_definition length="special" nprocs="1">
    <command_line>burgers_equation adjoint_bc.bml</command_line>
  </problem_definition>
  <variables>
    <variable name="forward_error" language="python">
from fluidity_tools import stat_parser as stat
forward_error = stat("bc.stat")["Fluid"]["VelocityError"]["l2norm"][-1]
    </variable>
    <variable name="adjoint_error" language="python">
from fluidity_tools import stat_parser as stat
adjoint_error = stat("bc_adjoint.stat")["Fluid"]["AdjointVelocityError"]["l2norm"][-1]
    </variable>
  </variables>
  <pass_tests>
    <test name="forward_error very small" language="python">
assert abs(forward_error) &lt; 1.0e-14
    </test>
    <test name="adjoint_error very small" language="python">
assert abs(adjoint_error) &lt; 1.0e-14
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/periodic_adaptivity/periodic_adaptivity.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>Periodic adaptivity</name>
  <owner userid="pfarrell"/>
  <tags>flml</tags>
  <problem_definition length="short" nprocs="1">
    <command_line>../../bin/periodise periodic_adaptivity.flml; fluidity -v2 -l periodic_adaptivity_periodised.flml </command_line>
  </problem_definition>
  <variables>
  </variables>
  <pass_tests>
    <test name="completion" language="python">
import fluidity_tools
stat = fluidity_tools.stat_parser("periodic_adaptivity.stat")
assert stat['ElapsedTime']['value'][-1] == 20.0
    </test>
    <test name="references" language="python">
assert "There are no references left" in open("fluidity.log-0").read()
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/burgers_tadj_mms/burgers_tadj_mms.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">
<testproblem>
  <name>Burgers Equation MMS</name>
  <owner userid="pef"/>
  <tags>burgers</tags>
  <problem_definition length="short" nprocs="1">
    <command_line>burgers_equation mms_A.bml; burgers_equation mms_B.bml; burgers_equation mms_C.bml; burgers_equation mms_D.bml</command_line>
  </problem_definition>
  <variables>
    <variable name="a_error" language="python">
from fluidity_tools import stat_parser as stat
from math import log

a_error = stat("mms_adjoint_A_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"]
    </variable>
    <variable name="b_error" language="python">
from fluidity_tools import stat_parser as stat
from math import log

b_error = stat("mms_adjoint_B_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"]
    </variable>
    <variable name="c_error" language="python">
from fluidity_tools import stat_parser as stat
from math import log

c_error = stat("mms_adjoint_C_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"]
    </variable>
    <variable name="d_error" language="python">
from fluidity_tools import stat_parser as stat
from math import log

d_error = stat("mms_adjoint_D_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"]
    </variable>
  </variables>
  <pass_tests>
    <test name="a_error" language="python">
      assert(abs(max(a_error)) &lt; 1.0e-10)
    </test>
    <test name="b_error" language="python">
      assert(abs(max(b_error)) &lt; 1.0e-10)
    </test>
    <test name="c_error" language="python">
      assert(abs(max(c_error)) &lt; 1.0e-10)
    </test>
    <test name="d_error" language="python">
      assert(abs(max(d_error)) &lt; 1.0e-10)
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/shoaling_tsunami_legacy/shoaling_tsunami_legacy.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<!-- Shoaling of a tsunami generated in deep water. Legacy discretisation used
  -->
<testproblem>
  <name>Shoaling of a tsunami generated in deep water. Legacy discretisation used.</name>
  <owner userid="piggott"/>
  <tags>flml</tags>
  <problem_definition length="special" nprocs="1">
    <command_line>dfluidity -v3 -l shoaling_tsunami_legacy.flml</command_line>
  </problem_definition>
  <variables>

  </variables>
  <pass_tests>

  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/hyperlight-bbop/hyperlight-bbop.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>hyperlight-bbop</name>
  <owner userid="ml805"/>
  <tags>flml hyperlight</tags>
    <problem_definition length="special" nprocs="1">
    <command_line>fluidity hyperlight-bbop.flml -l -v2  </command_line>
  </problem_definition>  
  <variables>  
    <variable name="FinalIrradianceMin" language="python">
import fluidity_tools
FinalIrradianceMin = fluidity_tools.stat_parser("hyperlight-bbop.stat")['Fluid']['IrradiancePAR']['min'][-1]
    </variable>    
  </variables>    

  <pass_tests> 
    <test name="Final irradiance greater 0" language="python">assert FinalIrradianceMin &gt; 0</test>
  </pass_tests>
</testproblem>

=== li12242/fluidity/tests/fldecomp/fldecomp.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">
<testproblem>
  <name>fldecomp</name>
  <owner userid="maddison"/>
  <problem_definition length = "short" nprocs = "1">
    <command_line>rm -f fldecomp.log; make clean-run; fldecomp -i triangle -n 4 -v cube > fldecomp.log</command_line>
  </problem_definition>
  <variables>
    <variable name = "partitions" language = "python">
import fluidity.diagnostics.triangletools as triangletools
partitions = []
for i in range(4):
  partitions.append(triangletools.ReadTriangle("cube_" + str(i)))
    </variable>
  </variables>
  <pass_tests>
    <test name = "Equal sized partitions (nodes)" language = "python">
import fluidity_tools
nodeCounts = []
for partition in partitions:
  nodeCounts.append(partition.NodeCoordsCount())
fluidity_tools.compare_variables([float(nodeCount) for nodeCount in nodeCounts[1:]], [float(nodeCounts[0]) for i in range(len(nodeCounts) - 1)], 0.15)
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>
