=== li12242/fluidity/tools/regressiontest.dtd
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--++ A dtd defining regression test problems                    ++-->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->

<!ELEMENT testproblem (name,tags,problem_definition,variables,pass_tests,warn_tests)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT owner (#PCDATA)>

<!ELEMENT tags (tag*)>
<!ELEMENT tag (#PCDATA)>

<!-- problem_definition might eventually contain information about
such things as number of nodes to run on. -->
<!ELEMENT problem_definition (command_line)>
<!ATTLIST problem_definition length (short|medium|long|special) #REQUIRED
                             nprocs CDATA #REQUIRED>

<!ELEMENT command_line (#PCDATA)>

<!ELEMENT variables (variable*)>

<!-- A variable (to be used in python tests) is defined by the value
of either a python expression or a bash expresion. -->
<!ELEMENT variable (#PCDATA)>
<!ATTLIST variable name NMTOKEN       #REQUIRED
                   language (python|bash) #REQUIRED>

<!ELEMENT pass_tests (test*)>

<!ELEMENT warn_tests (test*)>

<!-- A test is a python or bash expression which returns a python true 
value or bash successful completion for pass and a python 
false value or bash fail for fail. -->
<!ELEMENT test (#PCDATA)>
<!ATTLIST test name NMTOKEN       #REQUIRED
                   language (python|bash) #REQUIRED>

=== li12242/fluidity/tests/moving_lock_exchange_2d_dg/moving_lock_exchange_2d_dg.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>moving_lock_exchange_2d_dg</name>
  <owner userid="yves"/>
  <tags>flml</tags>
  <problem_definition length="special" nprocs="1">
    <command_line>dfluidity --xml moving_lock_exchange_2d_dg.flml </command_line>
    <!-- Two dimensional wind driven cavity. -->
  </problem_definition>
  <variables>
    <variable name="maxspeed" language="python">
      import fluidity_tools
      maxspeed =max(fluidity_tools.stat_parser("moving_lock_exchange.stat")['StratifiedFluid']['Velocity%magnitude']['max'])
    </variable>
  </variables>
  <pass_tests>
    <!-- l2norm should remain within 1% of a constant detemined analytically -->
    <test name="l2norm(speed) at last timestep" language="python">
      assert abs(maxspeed) &lt; 100000.0
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/cv_mixing_bin_test_serial/cv_mixing_bin_test_serial.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>Control volume, multi-material flow test for testing mixing stats</name>
  <owner userid="hhiester"/>
  <tags>flml</tags>
    <problem_definition length="short" nprocs="1">
    <command_line>fluidity -v3 -l cv_mixing_bin_test_serial.flml </command_line>
  </problem_definition>  
  <variables>  
    <variable name = "matvolume_base" language = "python">
import vtktools
matvolume_base = [[],[]]
filenames = ["base_mixing_bin_test_1.vtu","base_mixing_bin_test_4.vtu","base_mixing_bin_test_7.vtu"]
for file in filenames:
  matvolume_base[0].append(sum(vtktools.vtu(file).GetScalarField("Material1::MaterialVolume"))) 
  matvolume_base[1].append(sum(vtktools.vtu(file).GetScalarField("Material2::MaterialVolume")))  
    </variable> 
    <variable name = "matvolume" language = "python">
import vtktools
matvolume = [[],[]]
filenames = ["mixing_bin_test_1.vtu","mixing_bin_test_4.vtu","mixing_bin_test_7.vtu"]
for file in filenames:
  matvolume[0].append(sum(vtktools.vtu(file).GetScalarField("Material1::MaterialVolume"))) 
  matvolume[1].append(sum(vtktools.vtu(file).GetScalarField("Material2::MaterialVolume")))  
    </variable> 
     <variable name="mat2lbin" language="python">
import fluidity_tools
from fluidity_tools import stat_parser
mat2lbin = fluidity_tools.stat_parser("mixing_bin_test.stat")['Material2']['MaterialVolumeFraction']['mixing_bins%cv'][0][0]
    </variable>    
     <variable name="mat2ubin" language="python"> 
import fluidity_tools
from fluidity_tools import stat_parser
mat2ubin = fluidity_tools.stat_parser("mixing_bin_test.stat")['Material2']['MaterialVolumeFraction']['mixing_bins%cv'][1][0]
    </variable>    
     <variable name="mixing_stats" language="python"> 
# mixing stats will contain [normalised_cv, normalised_cg, unormalised_cv, unormalised_cg] 
# mixing stats, each of those contains the amount in the bins (bounds 0 and 1) over time
import fluidity_tools
from fluidity_tools import stat_parser
stat = fluidity_tools.stat_parser("./mixing_bin_test.stat")
time = stat['ElapsedTime']['value']
stat_type_a = ['cv','cg']
stat_type_b = ['normalised','unormalised']
mixing_stats = []
for types_b in stat_type_b:
  for types_a in stat_type_a:
    mixing_stats_current = []
    for i in range(len(stat['Material1']['MaterialVolumeFraction']['mixing_bins%'+types_a+'_'+types_b])):
      bin = []
      for j in range(len(stat['Material1']['MaterialVolumeFraction']['mixing_bins%'+types_a+'_'+types_b][i])):
        bin.append(stat['Material1']['MaterialVolumeFraction']['mixing_bins%'+types_a+'_'+types_b][i][j]) 
      mixing_stats_current.append(bin)
    mixing_stats_current.append([types_b + '_' + types_a])
    mixing_stats.append(mixing_stats_current) 
    </variable>  
  </variables>
    <pass_tests>  
    <test name = "check base and current volumes are same" language = "python">
for i in range(len(matvolume)):
  for j in range(len(matvolume[i])):
    print "i=", i
    print "j=", j
    tolerance = 1e-6
    if (j==2):tolerance = 1e-4
    print abs(matvolume[i][j]-matvolume_base[i][j])
    assert abs(matvolume[i][j]-matvolume_base[i][j]) &lt; tolerance
    </test>
    <test name="check lower mixing bin of material 2 is correct" language="python">
   assert abs(mat2lbin - (matvolume_base[0][0]/(matvolume_base[0][0]+matvolume_base[1][0]))) &lt; 1e-6
    </test>
    <test name="check upper mixing bin of material 2 is correct" language="python">
   assert abs(mat2ubin - (matvolume_base[1][0]/(matvolume_base[0][0]+matvolume_base[1][0]))) &lt; 1e-6
    </test>
    <test name = "check fixed normalised lower mixing bins of material 1 are correct " language = "python">
stat_type_a = ['cv','cg']
mixing_stats_pick = [0,3,6]
for i in [0,1]:
  for j in range(len(stat_type_a)):
    print mixing_stats[j][2]
    print abs(mixing_stats[j][0][mixing_stats_pick[i]] - (matvolume_base[1][i]/(matvolume_base[0][i]+matvolume_base[1][i])))
    tolerance = 1e-6
    if stat_type_a[j].split('_')[0] == 'cg': tolerance = 1e-1
    assert abs(mixing_stats[j][0][mixing_stats_pick[i]] - (matvolume_base[1][i]/(matvolume_base[0][i]+matvolume_base[1][i]))) &lt; tolerance
    </test>
    <test name = "check fixed normalised upper mixing bins of material 1 are correct " language = "python">
stat_type_a = ['cv','cg']
mixing_stats_pick = [0,3,6]
for i in [0,1]:
  for j in range(len(stat_type_a)):
    print mixing_stats[j][2]
    print abs(mixing_stats[j][1][mixing_stats_pick[i]] - matvolume_base[0][i]/(matvolume_base[0][i]+matvolume_base[1][i])) 
    tolerance = 1e-6
    if stat_type_a[j].split('_')[0] == 'cg': tolerance = 1e-1
    assert abs(mixing_stats[j][1][mixing_stats_pick[i]] - matvolume_base[0][i]/(matvolume_base[0][i]+matvolume_base[1][i])) &lt; tolerance
    </test>
    <test name = "check adapt normalised lower mixing bins of material 1 are correct " language = "python">
stat_type_a = ['cv','cg']
for j in range(len(stat_type_a)):
  print mixing_stats[j][2]
  print abs(mixing_stats[j][0][6] - matvolume_base[1][2]/(matvolume_base[0][2]+matvolume_base[1][2]))
  tolerance = 1e-1
  if stat_type_a[j].split('_')[0] == 'cg': tolerance = 1e-1
  assert abs(mixing_stats[j][0][6] - matvolume_base[1][2]/(matvolume_base[0][2]+matvolume_base[1][2])) &lt; tolerance
    </test>
    <test name = "check adapt normalised upper mixing bins of material 1 are correct " language = "python">
stat_type_a = ['cv','cg']
mixing_stats_pick = [0,3,6]
for j in range(len(stat_type_a)):
  print mixing_stats[j][2]
  print abs(mixing_stats[j][1][6] - matvolume_base[0][2]/(matvolume_base[0][2]+matvolume_base[1][2])) 
  tolerance = 1e-1
  if stat_type_a[j].split('_')[0] == 'cg': tolerance = 1e-1
  assert abs(mixing_stats[j][1][6] - matvolume_base[0][2]/(matvolume_base[0][2]+matvolume_base[1][2])) &lt; tolerance
    </test>
    <test name = "check fixed unormalised lower mixing bins of material 1 are correct " language = "python">
stat_type_a = ['cv','cg']
mixing_stats_pick = [0,3,6]
for i in [0,1]:
  for j in range(len(stat_type_a)):
    print mixing_stats[j+2][2]
    print abs(mixing_stats[j+2][0][mixing_stats_pick[i]] - matvolume_base[1][i]) 
    tolerance = 1e-6
    if stat_type_a[j].split('_')[0] == 'cg': tolerance = 1e-1
    assert abs(mixing_stats[j+2][0][mixing_stats_pick[i]] - matvolume_base[1][i]) &lt; tolerance
    </test>
    <test name = "check fixed unormalised upper mixing bins of material 1 are correct " language = "python">
stat_type_a = ['cv','cg']
mixing_stats_pick = [0,3,6]
for i in [0,1]:
  for j in range(len(stat_type_a)):
    print mixing_stats[j+2][2]
    print abs(mixing_stats[j+2][1][mixing_stats_pick[i]] - matvolume_base[0][i])
    tolerance = 1e-6
    if stat_type_a[j].split('_')[0] == 'cg': tolerance = 1e-1
    assert abs(mixing_stats[j+2][1][mixing_stats_pick[i]] - matvolume_base[0][i]) &lt; tolerance
    </test>
    <test name = "check adapt unormalised lower mixing bins of material 1 are correct " language = "python">
stat_type_a = ['cv','cg']
for j in range(len(stat_type_a)):
  print len(mixing_stats[j+2][0])
  print mixing_stats[j+2][2]
  print abs(mixing_stats[j+2][0][6] - matvolume_base[1][2])
  tolerance = 1e-2
  if stat_type_a[j].split('_')[0] == 'cg': tolerance = 1e-1
  assert abs(mixing_stats[j+2][0][6] - matvolume_base[1][2]) &lt; tolerance
    </test>
    <test name = "check adapt unormalised upper mixing bins of material 1 are correct " language = "python">
stat_type_a = ['cv','cg']
mixing_stats_pick = [0,3,6]
for j in range(len(stat_type_a)):
  print mixing_stats[j+2][2]
  print abs(mixing_stats[j+2][1][6] - matvolume_base[0][2])
  tolerance = 1e-1
  if stat_type_a[j].split('_')[0] == 'cg': tolerance = 1e-1
  assert abs(mixing_stats[j+2][1][6] - matvolume_base[0][2]) &lt; tolerance
    </test>
    <test name="check all normalised mixing bins of material 1 sum to 1" language="python">
stat_type_a = ['cv','cg']
for i in range(len(mixing_stats[0][0])):
  for j in range(len(stat_type_a)):
    print mixing_stats[j][2]
    print abs(mixing_stats[j][0][i] + mixing_stats[j][1][i] - 1.0)
    assert abs(mixing_stats[j][0][i] + mixing_stats[j][1][i] - 1.0) &lt; 1e-6
    </test>
    <test name="check all unormalised mixing bins of material 1 sum to right number" language="python">
stat_type_a = ['cv','cg']
for i in range(len(mixing_stats[0][0])):
  for j in range(len(stat_type_a)):
    print mixing_stats[j+2][2]
    print abs(((mixing_stats[j+2][0][i] + mixing_stats[j+2][1][i])/(matvolume_base[0][0]+matvolume_base[1][0])) - 1.0)
    assert abs(((mixing_stats[j+2][0][i] + mixing_stats[j+2][1][i])/(matvolume_base[0][0]+matvolume_base[1][0])) - 1.0) &lt; 1e-6
    </test>
    <test name="check lower and upper mixing bins of material 2 sum to 1" language="python">
   assert abs(mat2lbin + mat2ubin - 1.0) &lt; 1e-6
    </test>
  </pass_tests>
</testproblem>

=== li12242/fluidity/tests/mphase_divergence_free_velocity/mphase_divergence_free_velocity.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>

   <name>mphase_divergence_free_velocity</name>
   <owner userid="ctj10"/>
   <tags>flml</tags>
   
   <problem_definition length="short" nprocs="1">
      <command_line>make run</command_line>
      <!-- 3D test case to check that \sum{ div(vfrac*u) } is approximately equal to zero. -->
      <!-- This is based on the divergence_free_velocity test case by Simon Funke (see tests/divergence_free_velocity). -->
   </problem_definition>
   
   <variables>
      <variable name="SumVelocityDivergence" language="python">
from fluidity_tools import stat_parser
s = stat_parser("mphase_divergence_free_velocity.stat")
SumVelocityDivergence = s["Fluid1"]["SumVelocityDivergence"]["l2norm"]
      </variable>
   </variables>
   
   <pass_tests>
      <test name="\sum{div(vfrac*u)} is less than 1e-10." language="python">
assert(max(SumVelocityDivergence) &lt; 1e-10)
      </test>
   </pass_tests>
   
</testproblem>

=== li12242/fluidity/tests/cv_auxiliary_eqn/cv_auxiliary_eqn.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>Control volume, multi-material flow test</name>
  <owner userid="cwilson"/>
  <tags>flml solidity</tags>
    <problem_definition length="special" nprocs="1">
    <command_line>dfluidity -v2 -l cv_diffusion_input.flml </command_line>
  </problem_definition>  
  <variables>  
  </variables>
    <pass_tests>  
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/driven_cavity_coarse-inner_element_quadratic_pressure/driven_cavity_coarse-inner_element_quadratic_pressure.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<!-- Lid-driven cavity
  -->
<testproblem>
  <name>Lid-driven cavity run with the Inner Element sub-grid scale model</name>
  <owner userid="adam"/>
  <tags>flml</tags>
  <problem_definition length="short" nprocs="1">
    <command_line>dfluidity -v1 --xml driven_cavity_coarse-inner_element_quadratic_pressure.flml &gt; driven_cavity_coarse-inner_element_quadratic_pressure.log 2&gt;&amp;1</command_line>
  </problem_definition>
  <variables>

    <variable name="full_velocity_u_max" language="python">
import vtktools
import math
from numpy import max
u=vtktools.vtu("cavity_1.vtu")
vel=u.GetVectorField('InnerElementFullVelocity')
full_velocity_u_max=max(vel[:,0])
    </variable>

    <variable name="full_velocity_v_max" language="python">
import vtktools
import math
from numpy import max
u=vtktools.vtu("cavity_1.vtu")
vel=u.GetVectorField('InnerElementFullVelocity')
full_velocity_v_max=max(vel[:,1])
    </variable>

    <variable name="full_velocity_u_max_deviation" language="python">
import vtktools
import math
from numpy import max
u=vtktools.vtu("cavity_1.vtu")
vel=u.GetVectorField('InnerElementFullVelocity')
full_velocity_u_max=max(vel[:,0])
full_velocity_u_max_deviation=abs(full_velocity_u_max - 0.732116043568)/full_velocity_u_max
    </variable>

    <variable name="full_velocity_v_max_deviation" language="python">
import vtktools
import math
from numpy import max
u=vtktools.vtu("cavity_1.vtu")
vel=u.GetVectorField('InnerElementFullVelocity')
full_velocity_v_max=max(vel[:,1])
full_velocity_v_max_deviation=abs(full_velocity_v_max - 0.956379830837)/full_velocity_v_max
    </variable>

  </variables>
  <pass_tests>
    <test name="Maximum full velocity component u - checking this is less than 2.0 " language="python">
    assert full_velocity_u_max &lt; 2.0
    </test>
    <test name="Maximum full velocity component u - checking this is greater than 0.7 " language="python">
    assert full_velocity_u_max &gt; 0.7
    </test>
    <test name="Accurate full velocity component u comparison with SVN 7320.  Checks the computed max u velocity component is within 1% of the value from the code of revision 7320." language="python">
    assert full_velocity_u_max_deviation &lt; 0.01
    </test>

    <test name="Maximum full velocity component v - checking this is less than 1.0 " language="python">
    assert full_velocity_v_max &lt; 1.0
    </test>
    <test name="Maximum full velocity component v - checking this is greater than 0.2 " language="python">
    assert full_velocity_v_max &gt; 0.2
    </test>
    <test name="Accurate full velocity component v comparison with SVN 7320.  Checks the computed max v velocity component is within 1% of the value from the code of revision 7320." language="python">
    assert full_velocity_v_max_deviation &lt; 0.01
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/rad_1d_3grp_hom_inf_eig/rad_1d_3grp_hom_inf_eig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>rad_1d_3grp_hom_inf_eig</name>
  <owner userid="btollit"/>
  <tags>flml radiation</tags>
  <problem_definition length="short" nprocs="1">
    <command_line>
       ../../bin/fluidity rad_1d_3grp_hom_inf_eig.flml 
    </command_line>
    <!-- Radiation diffusion eigenvalue problem with 1 material, 3 energy groups no upscatter with all reflective BC using a 1d geometry compared to analytic solution for the keff and flux ratio, this is ABC problem 74-->
  </problem_definition>
  <variables>
    <variable name="ParticleKeffneutron" language="python">
from fluidity_tools import stat_parser as stat
ParticleKeffneutron = stat("rad_1d_3grp_hom_inf_eig.stat")["ParticleKeffneutron1"]["Value"][0]
    </variable>
    <variable name="FluxGroup1Moment1neutron" language="python">
import vtktools
v = vtktools.vtu("rad_1d_3grp_hom_inf_eig_1.vtu")
FluxGroup1Moment1neutron = max(v.GetScalarRange("ParticleFluxGroup1Moment1neutron"))
    </variable>
    <variable name="FluxGroup2Moment1neutron" language="python">
import vtktools
v = vtktools.vtu("rad_1d_3grp_hom_inf_eig_1.vtu")
FluxGroup2Moment1neutron = max(v.GetScalarRange("ParticleFluxGroup2Moment1neutron"))
    </variable>
    <variable name="FluxGroup3Moment1neutron" language="python">
import vtktools
v = vtktools.vtu("rad_1d_3grp_hom_inf_eig_1.vtu")
FluxGroup3Moment1neutron = max(v.GetScalarRange("ParticleFluxGroup3Moment1neutron"))
    </variable>    
  </variables>
  <pass_tests>
    <test name="Check ParticleKeffneutron against analytic with tolerance 1.0e-06" language="python">
analytic_keff = 1.6
print 'Relative error compared to analytic: ',abs((ParticleKeffneutron - analytic_keff)/analytic_keff)
assert abs((ParticleKeffneutron - analytic_keff)/analytic_keff) &lt; 1.0e-06
    </test>
    <test name="Check Flux ratio of group 2 moment 1 to group 1 moment 1 against analytic with tolerance 1.0e-06" language="python">
analytic_flux_ratio = 0.480
flux_ratio = FluxGroup2Moment1neutron / FluxGroup1Moment1neutron 
print 'Relative error compared to analytic: ',abs((flux_ratio - analytic_flux_ratio)/analytic_flux_ratio)
assert abs((flux_ratio - analytic_flux_ratio)/analytic_flux_ratio) &lt; 1.0e-06
    </test>
    <test name="Check Flux ratio of group 3 moment 1 to group 2 moment 1 against analytic with tolerance 1.0e-06" language="python">
analytic_flux_ratio = 0.3125
flux_ratio = FluxGroup3Moment1neutron / FluxGroup2Moment1neutron 
print 'Relative error compared to analytic: ',abs((flux_ratio - analytic_flux_ratio)/analytic_flux_ratio)
assert abs((flux_ratio - analytic_flux_ratio)/analytic_flux_ratio) &lt; 1.0e-06
    </test>
    <test name="Check Flux ratio of group 3 moment 1 to group 1 moment 1 against analytic with tolerance 1.0e-06" language="python">
analytic_flux_ratio = 0.15
flux_ratio = FluxGroup3Moment1neutron / FluxGroup1Moment1neutron 
print 'Relative error compared to analytic: ',abs((flux_ratio - analytic_flux_ratio)/analytic_flux_ratio)
assert abs((flux_ratio - analytic_flux_ratio)/analytic_flux_ratio) &lt; 1.0e-06
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/gls-Kato_Phillips-mixed_layer_depth/gls-Kato_Phillips-mixed_layer_depth.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>gls-Kato_Phillips-mixed_layer_depth-k_epsilon</name>
  <owner userid="piggott"/>
  <tags>flml</tags>
    <problem_definition length="medium" nprocs="1">
    <command_line>dfluidity gls-Kato_Phillips-mixed_layer_depth-k_epsilon-CanutoA.flml &gt; /dev/null 2&gt;&amp;1;</command_line>
  </problem_definition>  
  <variables>  

    <variable name="FinalTime" language="python">
import fluidity_tools
FinalTime = fluidity_tools.stat_parser("gls-Kato_Phillips-mixed_layer_depth-k_epsilon-CanutoA.stat")['ElapsedTime']['value'][-1]
    </variable>


  <variable name="CanutoA_MLD" language="python">

from numpy import arange,concatenate,array,argsort
import glob
import os
import sys
import vtktools
import math
import re 
from math import sqrt


#### taken from http://www.codinghorror.com/blog/archives/001018.html  #######
def sort_nicely( l ): 
  """ Sort the given list in the way that humans expect. 
  """ 
  convert = lambda text: int(text) if text.isdigit() else text 
  alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
  l.sort( key=alphanum_key ) 
##############################################################################


# compute the mixed layer depth over time
def MLD(filelist):
  x0 = 500.0
  
  tke0 = 1.0e-5
  
  times = []
  depths = []
  Dm = []
  for file in filelist:
     print file
     try:
       os.stat(file)
     except:
       print "No such file: %s" % file
       sys.exit(1)
     
     num = int(file.split(".vtu")[0].split('_')[-1])
     if (num &lt; 1):
       continue
     
     u=vtktools.vtu(file)
     time = u.GetScalarField('Time')
     tt = time[0]
     kk = u.GetScalarField('GLSTurbulentKineticEnergy')
     pos = u.GetLocations()
     
     xyzkk = []
     for i in range(0,len(kk)):
        if( abs(pos[i,0] - x0) &lt; 0.1 ):
           xyzkk.append((pos[i,0],-pos[i,1],pos[i,2],(kk[i])))
     
     xyzkkarr = vtktools.arr(xyzkk)
     III = argsort(xyzkkarr[:,1])
     xyzkkarrsort = xyzkkarr[III,:]
     ggg = ((xyzkkarrsort[:,3]) &gt; tke0).nonzero()
     LL = 0
     while(ggg[-1][LL]==LL) and (LL+1&lt;len(ggg[-1])):
       LL = LL + 1
     zz = -xyzkkarrsort[:,1]
     zza = zz[LL+1]
     zzb = zz[LL]
     kea = xyzkkarrsort[LL+1,3]
     keb = xyzkkarrsort[LL,3]
     print tt/3600,(zza-(zza-zzb)*(((keb)-tke0)/((keb)-(kea))))
     times.append(tt/3600)
     depths.append(-1.0*(zza-(zza-zzb)*(((keb)-tke0)/((keb)-(kea)))))
     Dm.append(1.05*1.0e-2*(1.0/sqrt(0.01))*sqrt(tt))
     
  return times, depths, Dm
  
filelist = glob.glob("gls-Kato_Phillips-mixed_layer_depth-k_epsilon-CanutoA_*.vtu")
sort_nicely(filelist)
CanutoA_MLD = MLD(filelist)
    </variable>


  </variables>    

  <pass_tests> 
    <test name="Final time greater than 1.0e5" language="python">
assert FinalTime &gt; 1.0e5
    </test>
    <test name ="Check mixed layed depth at times from 1 hr to 30 hrs is within 5.5 metres of experimentally fitted values. K-epsilon with Canuto (version A) 2001 stability functions." language="python">
from numpy import array, all
print ( array(CanutoA_MLD[1]) - array(CanutoA_MLD[2]) )
assert (all( abs(array(CanutoA_MLD[1]) - array(CanutoA_MLD[2]) ) &lt; 5.5))
    </test>
  </pass_tests>
</testproblem>

=== li12242/fluidity/tests/burgers_tadj_timestep/burgers_tadj_timestep.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">
<testproblem>
  <name>Burgers Equation MMS</name>
  <owner userid="pef"/>
  <tags>burgers</tags>
  <problem_definition length="special" nprocs="1">
    <command_line>burgers_equation mms_A.bml; burgers_equation mms_B.bml; burgers_equation mms_C.bml; burgers_equation mms_D.bml; burgers_equation mms_E.bml</command_line>
  </problem_definition>
  <variables>
    <variable name="gradient" language="python">
gradient = -533.3333333333 # from sage
    </variable>
    <variable name="gradient_a" language="python">
from fluidity_tools import stat_parser as stat
gradient_a = sum(stat("mms_adjoint_A_adjoint.stat")["Fluid"]["dJdm"]["max"])
    </variable>
    <variable name="gradient_b" language="python">
from fluidity_tools import stat_parser as stat
gradient_b = sum(stat("mms_adjoint_B_adjoint.stat")["Fluid"]["dJdm"]["max"])
    </variable>
    <variable name="gradient_c" language="python">
from fluidity_tools import stat_parser as stat
gradient_c = sum(stat("mms_adjoint_C_adjoint.stat")["Fluid"]["dJdm"]["max"])
    </variable>
    <variable name="gradient_d" language="python">
from fluidity_tools import stat_parser as stat
gradient_d = sum(stat("mms_adjoint_D_adjoint.stat")["Fluid"]["dJdm"]["max"])
    </variable>
    <variable name="gradient_e" language="python">
from fluidity_tools import stat_parser as stat
gradient_e = sum(stat("mms_adjoint_E_adjoint.stat")["Fluid"]["dJdm"]["max"])
    </variable>
    <variable name="conv_ab" language="python">
from fluidity_tools import stat_parser as stat
from math import log
gradient = -533.3333333333 # from sage
err_a = abs(gradient - sum(stat("mms_adjoint_A_adjoint.stat")["Fluid"]["dJdm"]["max"]))
err_b = abs(gradient - sum(stat("mms_adjoint_B_adjoint.stat")["Fluid"]["dJdm"]["max"]))
conv_ab = log(err_a/err_b, 2)
    </variable>
    <variable name="conv_bc" language="python">
from fluidity_tools import stat_parser as stat
from math import log
gradient = -533.3333333333 # from sage
err_b = abs(gradient - sum(stat("mms_adjoint_B_adjoint.stat")["Fluid"]["dJdm"]["max"]))
err_c = abs(gradient - sum(stat("mms_adjoint_C_adjoint.stat")["Fluid"]["dJdm"]["max"]))
conv_bc = log(err_b/err_c, 2)
    </variable>
    <variable name="conv_cd" language="python">
from fluidity_tools import stat_parser as stat
from math import log
gradient = -533.3333333333 # from sage
err_c = abs(gradient - sum(stat("mms_adjoint_C_adjoint.stat")["Fluid"]["dJdm"]["max"]))
err_d = abs(gradient - sum(stat("mms_adjoint_D_adjoint.stat")["Fluid"]["dJdm"]["max"]))
conv_cd = log(err_c/err_d, 2)
    </variable>
    <variable name="conv_de" language="python">
from fluidity_tools import stat_parser as stat
from math import log
gradient = -533.3333333333 # from sage
err_d = abs(gradient - sum(stat("mms_adjoint_D_adjoint.stat")["Fluid"]["dJdm"]["max"]))
err_e = abs(gradient - sum(stat("mms_adjoint_E_adjoint.stat")["Fluid"]["dJdm"]["max"]))
conv_de = log(err_d/err_e, 2)
    </variable>
  </variables>
  <pass_tests>
    <test name="conv_ab > 1.9" language="python">
assert conv_ab &gt; 1.9
    </test>
    <test name="conv_bc > 1.9" language="python">
assert conv_bc &gt; 1.9
    </test>
    <test name="conv_cd > 1.9" language="python">
assert conv_cd &gt; 1.9
    </test>
    <test name="conv_de > 1.9" language="python">
assert conv_de &gt; 1.9
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>
