=== li12242/fluidity/tools/regressiontest.dtd
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
<!--++ A dtd defining regression test problems                    ++-->
<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->

<!ELEMENT testproblem (name,tags,problem_definition,variables,pass_tests,warn_tests)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT owner (#PCDATA)>

<!ELEMENT tags (tag*)>
<!ELEMENT tag (#PCDATA)>

<!-- problem_definition might eventually contain information about
such things as number of nodes to run on. -->
<!ELEMENT problem_definition (command_line)>
<!ATTLIST problem_definition length (short|medium|long|special) #REQUIRED
                             nprocs CDATA #REQUIRED>

<!ELEMENT command_line (#PCDATA)>

<!ELEMENT variables (variable*)>

<!-- A variable (to be used in python tests) is defined by the value
of either a python expression or a bash expresion. -->
<!ELEMENT variable (#PCDATA)>
<!ATTLIST variable name NMTOKEN       #REQUIRED
                   language (python|bash) #REQUIRED>

<!ELEMENT pass_tests (test*)>

<!ELEMENT warn_tests (test*)>

<!-- A test is a python or bash expression which returns a python true 
value or bash successful completion for pass and a python 
false value or bash fail for fail. -->
<!ELEMENT test (#PCDATA)>
<!ATTLIST test name NMTOKEN       #REQUIRED
                   language (python|bash) #REQUIRED>

=== li12242/fluidity/tests/diffusion_2d_p0_adaptive_parallel/diffusion_2d_p0_adaptive_parallel.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>heat_2d_dg</name>
  <owner userid="cwilson"/>
  <tags>flml zoltan</tags>
  <problem_definition length="medium" nprocs="1">
    <command_line>mpiexec -np 3 ../../bin/fluidity -v2 -l heat.flml </command_line>
    <!-- Two dimensional diffusion only problem. -->
  </problem_definition>
  <variables>
    <variable name="detectors" language="python">
from fluidity_tools import stat_parser
detectors = stat_parser("heat.detectors")
    </variable>
    <variable name="finish_time" language="python">
from fluidity_tools import stat_parser
s = stat_parser("heat.stat")
finish_time = s["ElapsedTime"]["value"][-1]
    </variable>
    <variable name="no_nodes" language="python">
from fluidity_tools import stat_parser
s = stat_parser("heat.stat")
no_nodes = s["CoordinateMesh"]["nodes"]
    </variable>
    <variable name="tracer_integral" language="python">
from fluidity_tools import stat_parser
s = stat_parser("heat.stat")
tracer_integral = s["Water"]["Tracer"]["integral"]
    </variable>
    <variable name="tracer_error" language="python">
from fluidity_tools import stat_parser
s = stat_parser("heat.stat")
tracer_error = s["Water"]["ScalarAbsoluteDifference"]["max"]
    </variable>
    <variable name="regionids_integral" language="python">
from fluidity_tools import stat_parser
s = stat_parser("heat.stat")
regionids_integral = s["Water"]["RegionIDs"]["integral"]
    </variable>
    <variable name="regionid_upperleft" language="python">
import vtktools
import glob
import fluidity.diagnostics.vtutools as vtutools
from numpy import array, concatenate, zeros

regionid_upperleft = []
centre = array([-0.75,0.5])

posx = []
posx.append([centre[0]])
posx.append([centre[0]-1./6.])
posx.append([centre[0]+1./6.])
posx.append([centre[0]+1./6.])
posx.append([centre[0]-1./6.])
posx = array(posx)

posy = []
posy.append([centre[1]])
posy.append([centre[1]-1./4.])
posy.append([centre[1]-1./4.])
posy.append([centre[1]+1./4.])
posy.append([centre[1]+1./4.])
posy = array(posy)

posz = zeros((len(posx),1))

pos = concatenate((posx, posy, posz), 1)

files = glob.glob("heat_*.pvtu")
for f in files:
  pvtu = vtktools.vtu(f)
  vtu = vtutools.VtuFromPvtu(pvtu)
  regionid_upperleft.append(vtu.ProbeData(pos, "RegionIDs"))

regionid_upperleft = array(regionid_upperleft)
    </variable>
    <variable name="regionid_upperright" language="python">
import vtktools
import glob
import fluidity.diagnostics.vtutools as vtutools
from numpy import array, concatenate, zeros

regionid_upperright = []
centre = array([-0.25,0.5])

posx = []
posx.append([centre[0]])
posx.append([centre[0]-1./6.])
posx.append([centre[0]+1./6.])
posx.append([centre[0]+1./6.])
posx.append([centre[0]-1./6.])
posx = array(posx)

posy = []
posy.append([centre[1]])
posy.append([centre[1]-1./4.])
posy.append([centre[1]-1./4.])
posy.append([centre[1]+1./4.])
posy.append([centre[1]+1./4.])
posy = array(posy)

posz = zeros((len(posx),1))

pos = concatenate((posx, posy, posz), 1)

files = glob.glob("heat_*.pvtu")
for f in files:
  pvtu = vtktools.vtu(f)
  vtu = vtutools.VtuFromPvtu(pvtu)
  regionid_upperright.append(vtu.ProbeData(pos, "RegionIDs"))

regionid_upperright = array(regionid_upperright)
    </variable>
    <variable name="regionid_lowerleft" language="python">
import vtktools
import glob
import fluidity.diagnostics.vtutools as vtutools
from numpy import array, concatenate, zeros

regionid_lowerleft = []
centre = array([-0.75,-0.5])

posx = []
posx.append([centre[0]])
posx.append([centre[0]-1./6.])
posx.append([centre[0]+1./6.])
posx.append([centre[0]+1./6.])
posx.append([centre[0]-1./6.])
posx = array(posx)

posy = []
posy.append([centre[1]])
posy.append([centre[1]-1./4.])
posy.append([centre[1]-1./4.])
posy.append([centre[1]+1./4.])
posy.append([centre[1]+1./4.])
posy = array(posy)

posz = zeros((len(posx),1))

pos = concatenate((posx, posy, posz), 1)

files = glob.glob("heat_*.pvtu")
for f in files:
  pvtu = vtktools.vtu(f)
  vtu = vtutools.VtuFromPvtu(pvtu)
  regionid_lowerleft.append(vtu.ProbeData(pos, "RegionIDs"))

regionid_lowerleft = array(regionid_lowerleft)
    </variable>
    <variable name="regionid_lowerright" language="python">
import vtktools
import glob
import fluidity.diagnostics.vtutools as vtutools
from numpy import array, concatenate, zeros

regionid_lowerright = []
centre = array([-0.25,-0.5])

posx = []
posx.append([centre[0]])
posx.append([centre[0]-1./6.])
posx.append([centre[0]+1./6.])
posx.append([centre[0]+1./6.])
posx.append([centre[0]-1./6.])
posx = array(posx)

posy = []
posy.append([centre[1]])
posy.append([centre[1]-1./4.])
posy.append([centre[1]-1./4.])
posy.append([centre[1]+1./4.])
posy.append([centre[1]+1./4.])
posy = array(posy)

posz = zeros((len(posx),1))

pos = concatenate((posx, posy, posz), 1)

files = glob.glob("heat_*.pvtu")
for f in files:
  pvtu = vtktools.vtu(f)
  vtu = vtutools.VtuFromPvtu(pvtu)
  regionid_lowerright.append(vtu.ProbeData(pos, "RegionIDs"))

regionid_lowerright = array(regionid_lowerright)
    </variable>
  </variables>
  <pass_tests>
    <test name="finish time is 1000" language="python">
assert abs(finish_time - 1000) &lt; 1e-9
    </test>
    <test name="no. nodes is initially 231" language="python">
assert abs(no_nodes[0] - 231) &lt; 1e-9
    </test>
    <test name="no. nodes is constant" language="python">
import numpy
assert(numpy.all(abs(no_nodes[1:] - no_nodes[0]) &lt; 1e-9))
    </test>
    <test name="tracer integral is initially 1.0" language="python">
assert abs(tracer_integral[0] - 1.0) &lt; 1e-9
    </test>
    <test name="tracer integral is constant" language="python">
import numpy
assert(numpy.all(abs(tracer_integral[1:] - tracer_integral[0]) &lt; 1e-9))
    </test>
    <test name="tracer error is initially less than 0.01" language="python">
assert tracer_error[0] &lt; 0.01 
    </test>
    <test name="tracer error less than 0.01" language="python">
import numpy
assert(numpy.all(abs(tracer_error[1:]-tracer_error[0]) &lt; 1.e-9)) 
    </test>
    <test name="regionids integral is initially 39.0" language="python">
assert abs(regionids_integral[0] - 39.0) &lt; 1e-9
    </test>
    <test name="regionids integral is constant" language="python">
import numpy
assert(numpy.all(abs(regionids_integral[1:] - regionids_integral[0]) &lt; 1e-9))
    </test>
    <test name="regionids upper left is 21" language="python">
import numpy
assert(numpy.all(abs(regionid_upperleft - 21.) &lt; 1e-9))
    </test>
    <test name="regionids upper right is 20" language="python">
import numpy
assert(numpy.all(abs(regionid_upperright - 20.) &lt; 1e-9))
    </test>
    <test name="regionids lower left is 18" language="python">
import numpy
assert(numpy.all(abs(regionid_lowerleft - 18.) &lt; 1e-9))
    </test>
    <test name="regionids lower right is 19" language="python">
import numpy
assert(numpy.all(abs(regionid_lowerright - 19.) &lt; 1e-9))
    </test>
    <test name="regionids initial" language="python">
import numpy
assert(numpy.array([detectors["Water"]["RegionIDs"][d][0]&gt;17
                   for d in detectors["Water"]["RegionIDs"].keys()], dtype=bool).all())
    </test>
<!--    <test name="regionids detectors" language="python">
import numpy
for d in detectors["Water"]["RegionIDs"].keys():
  print d, detectors["Water"]["RegionIDs"][d][0]
assert(numpy.array([numpy.all(abs(detectors["Water"]["RegionIDs"][d][1:]-detectors["Water"]["RegionIDs"][d][0])&lt;1.e-9) 
                              for d in detectors["Water"]["RegionIDs"].keys()], dtype=bool).all())
    </test>-->
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/square-tiny-adaptive/square-tiny-adaptive.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">
<testproblem>
  <name>Square tiny memory test (with mesh adaptivity)</name>
  <owner userid="maddison"/>
  <tags>flml</tags>
  <problem_definition length = "special" nprocs = "1">
    <command_line>make clean-run-debug &amp;&amp; rm -f memory.log &amp;&amp; ../../scripts/memwrap -t 1 dfluidity -v2 -l square-tiny-adaptive.flml > memory.log</command_line>
  </problem_definition>
  <variables>
    <variable name = "timesteps" language = "python">
import fluidity_tools
s = fluidity_tools.stat_parser("square-tiny-adaptive.stat")
times = s["ElapsedTime"]["value"]
timesteps = len(times)
    </variable>
    <variable name = "solvers_converged" language = "python">
import os
files = os.listdir("./")
solvers_converged = not "matrixdump" in files and not "matrixdump.info" in files 
    </variable>
    <variable name = "memory_usage" language = "python">
class MemoryUsage():
  def __init__(self):
    self.usage = []
    
    return
    
  def __str__(self):
    string = "Memory usage, " + str(len(self.usage)) + " entries"
    if len(self.usage) &gt; 0:
      string += "\nFinal entry: " + str(self.usage[-1])
    
    return string
    
fileHandle = open("memory.log", "r")
memory_usage = MemoryUsage()
line = fileHandle.readline().strip()
while len(line) &gt; 0:
  time, rssize, vsize = line.split()
  time = float(time)
  rssize = int(rssize)
  vsize = int(vsize)
  memory_usage.usage.append([time, rssize, vsize])
  line = fileHandle.readline().strip()
    </variable>
  </variables>
  <pass_tests>
    <test name = "Simulation completed" language = "python">
assert(timesteps == 1000)
    </test>
    <test name = "Solvers converged" language = "python">
assert(solvers_converged)
    </test>
    <test name = "Leak detection" language = "python">
usage = memory_usage.usage
finalTime, finalRssize, finalVsize = usage[-1]
for i in range(len(usage) / 2):
  time, rssize, vsize = usage[len(usage) - i - 2]
  assert(rssize &gt;= finalRssize)
  assert(vsize &gt;= finalVsize)
    </test>
  </pass_tests>
  <warn_tests>
    <test name = "Limited resident set size" language = "python">
usage = memory_usage.usage
print "Final resident set size: " + str(usage[-1][1])
assert(usage[-1][1] &lt; 35000)
    </test>
    <test name = "Limited virtual memory size" language = "python">
usage = memory_usage.usage
print "Final virtual memory size: " + str(usage[-1][2])
assert(usage[-1][2] &lt; 150000)
    </test>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/rad_1d_2grp_hom_zerobc_eig/rad_1d_2grp_hom_zerobc_eig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>rad_1d_2grp_hom_zerobc_eig</name>
  <owner userid="btollit"/>
  <tags>flml</tags>
  <problem_definition length="short" nprocs="1">
    <command_line>
       fluidity rad_1d_2grp_hom_zerobc_eig.flml 
    </command_line>
    <!-- Radiation diffusion eigenvalue problem with one material, two energy groups no upscatter with all zero BC using a 1d geometry compared to PANTHER reference solution for the keff -->
  </problem_definition>
  <variables>
    <variable name="Keffneutron" language="python">
from fluidity_tools import stat_parser as stat
Keffneutron = stat("rad_1d_2grp_hom_zerobc_eig.stat")["NeutralParticleKeffneutron1"]["Value"][0]
    </variable>
  </variables>
  <pass_tests>
    <test name="Check Keffneutron against PANTHER reference" language="python">
reference_keff = 1.0
print 'Relative error compared to reference: ',abs((Keffneutron - reference_keff)/reference_keff)
assert abs((Keffneutron - reference_keff)/reference_keff) &lt; 3.5e-05
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/MY25-KatoPhilips/MY.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>MY</name>
  <owner userid="piggott"/>
  <tags>flml</tags>
  <problem_definition length="special" nprocs="1">
    <command_line>dfluidity -v3 -x MY.flml &gt; MY.log 2&gt;&amp;1; </command_line>
  </problem_definition>
  <variables>
  </variables>
  <pass_tests>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/burgers_mms_adjoint/burgers_mms_adjoint.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">
<testproblem>
  <name>Burgers Equation MMS</name>
  <owner userid="pef"/>
  <tags>burgers</tags>
  <problem_definition length="short" nprocs="1">
    <command_line>burgers_equation mms_A.bml; burgers_equation mms_B.bml; burgers_equation mms_C.bml; burgers_equation mms_D.bml; burgers_equation mms_E.bml</command_line>
  </problem_definition>
  <variables>
    <variable name="ab_error" language="python">
from fluidity_tools import stat_parser as stat
from math import log

a_error = stat("mms_adjoint_A_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"][-1]
b_error = stat("mms_adjoint_B_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"][-1]

ab_ratio = a_error / b_error
ab_error = [log(ab_ratio, 2)]
    </variable>
    <variable name="bc_error" language="python">
from fluidity_tools import stat_parser as stat
from math import log

b_error = stat("mms_adjoint_B_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"][-1]
c_error = stat("mms_adjoint_C_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"][-1]

bc_ratio = b_error / c_error
bc_error = [log(bc_ratio, 2)]
    </variable>
    <variable name="cd_error" language="python">
from fluidity_tools import stat_parser as stat
from math import log

c_error = stat("mms_adjoint_C_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"][-1]
d_error = stat("mms_adjoint_D_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"][-1]

cd_ratio = c_error / d_error
cd_error = [log(cd_ratio, 2)]
    </variable>
    <variable name="de_error" language="python">
from fluidity_tools import stat_parser as stat
from math import log

d_error = stat("mms_adjoint_D_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"][-1]
e_error = stat("mms_adjoint_E_adjoint.stat")["Fluid"]["AdjointError"]["l2norm"][-1]

de_ratio = d_error / e_error
de_error = [log(de_ratio, 2)]
    </variable>
  </variables>
  <pass_tests>
    <test name="ab_convergence_stat: L2 order in [1.8,2.2]" language="python">
assert(abs(ab_error[0]-2.0) &lt; 0.2)
    </test>
    <test name="bc_convergence_stat: L2 order in [1.8,2.2]" language="python">
assert(abs(bc_error[0]-2.0) &lt; 0.2)
    </test>
    <test name="cd_convergence_stat: L2 order in [1.8,2.2]" language="python">
assert(abs(cd_error[0]-2.0) &lt; 0.2)
    </test>
    <test name="de_convergence_stat: L2 order in [1.8,2.2]" language="python">
assert(abs(de_error[0]-2.0) &lt; 0.2)
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/internal_wave/internal_wave.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>Internal Wave</name>
  <owner userid="bmartin"/>
  <tags>flml</tags>
  <problem_definition length="medium" nprocs="1">
    <command_line>fluidity -v3 -l --xml internal_wave.flml &gt; /dev/null 2&gt;&amp;1</command_line>
  </problem_definition>
  <variables>
    <variable name="speednorm" language="python">
import fluidity_tools
speednorm =fluidity_tools.stat_parser("InternalWave.stat")['StratifiedFluid']['Velocity%magnitude']['l2norm'][-1]
    </variable>
  </variables>
  <pass_tests>
    <!-- l2norm should remain within 1% of a constant detemined analytically -->
    <test name="l2norm(speed) at last timestep" language="python">
assert abs(speednorm - 0.0017479) &lt; 0.0000175
    </test>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/elastic-cube/elastic-cube.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>Visco-elastic solid block test</name>
  <owner userid="cwilson"/>
  <tags>flml solidity</tags>
    <problem_definition length="medium" nprocs="1">
    <command_line>dfluidity --xml lagrangian_elastic_cube.flml  </command_line>
  </problem_definition>  
  <variables>  
    <variable name="velocity" language="python">
import fluidity_tools
velocity = fluidity_tools.stat_parser("lagrangian_elastic_cube.stat")['Solid']['Velocity%magnitude']['max'][-1]
    </variable>    
    <variable name="mnpressure" language="python">
import fluidity_tools
mnpressure = fluidity_tools.stat_parser("lagrangian_elastic_cube.stat")['Solid']['Pressure']['min'][-1]
    </variable>    
    <variable name="mxpressure" language="python">
import fluidity_tools
mxpressure = fluidity_tools.stat_parser("lagrangian_elastic_cube.stat")['Solid']['Pressure']['max'][-1]
    </variable>    
  </variables>
    <pass_tests>  
    <test name="check maximum speed is less than 5e-4" language="python">
	assert abs(velocity) &lt; 5e-4
    </test>    
    <test name="check pressure difference is not zero (to see if pressure solution is happening)" language="python">
	assert abs(mxpressure-mnpressure) &gt; 1e-6
    </test>    
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>

=== li12242/fluidity/tests/rossby_equatorial_soliton/rossby_equatorial_soliton.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testproblem SYSTEM "regressiontest.dtd">

<testproblem>
  <name>Standing free surface wave in channel.</name>
  <owner userid="piggott"/>
  <problem_definition length="special" nprocs="1">
    <command_line>dfluidity -v3 -l -x rossby_equatorial_soliton.flml</command_line>
  </problem_definition>
  <variables>
  </variables>
  <pass_tests>
  </pass_tests>
  <warn_tests>
  </warn_tests>
</testproblem>
